// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkrzkunmhnqpupaflowk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprcnprdW5taG5xcHVwYWZsb3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTIyNzQsImV4cCI6MjA2NzEyODI3NH0.QjmxmRgjNZlszGgl2gIuOnrgA7btnPqZ9xZbqZcpo7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});